services:
  navidrofm:
    image: ghcr.io/4rft5/navidrofm:latest
    container_name: navidrofm
    restart: unless-stopped
    environment:
      TZ: Your/Timezone
      LASTFM_USERNAME: username
      NAVIDROME_URL: http://navidrome:4533
      NAVIDROME_USERNAME: username
      NAVIDROME_PASSWORD: password
      SYNC_SCHEDULE: "0 4 * * 1"
      RECOMMENDED: "true"
      RECOMMENDED_TRACKS: "25"
      MIX: "true"
      MIX_TRACKS: "25"
      LIBRARY: "true"
      LIBRARY_TRACKS: "50"
      RUN_ON_STARTUP: "false"
      PUID: 1000
      PGID: 1000
    volumes:
      - /your/music/library:/music
      - ./cookies.txt:/app/cookies/cookies.txt
